import React, { useState } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Brand from "../components/Brand";
import CardEvent from "../components/CardEvent";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Statistics from "../components/Statistics";
import Stories from "../components/Stories";
import { getData } from "../utils/fetchData";

export default function Home({ data }) {
  // const [searchTerm, setSearchTerm] = useState("");
  // const [filteredData, setFilteredData] = useState(data);

  // const handleSearch = (term) => {
  //   setSearchTerm(term);
  //   const lowercasedTerm = term.toLowerCase();
  //   const filtered =
  //     lowercasedTerm === ""
  //       ? data
  //       : data.filter((event) => {
  //           const titleMatch = event.title
  //             .toLowerCase()
  //             .includes(lowercasedTerm);
  //           const categoryMatch =
  //             event.category &&
  //             event.category.name.toLowerCase().includes(lowercasedTerm);
  //           return titleMatch || categoryMatch;
  //         });
  //   setFilteredData(filtered);
  // };

  return (
    <>
      <Head>
        <title>NgeventKuy || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Header />
      <Brand />
      <CardEvent
        data={data}
        title="Featured Events"
        subTitle="Find your best event here"
      />
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData("api/v1/events");
  const res = req.data;

  return {
    props: { data: res },
  };
}
