/* eslint-disable @next/next/no-img-element */
import moment from "moment";
import Head from "next/head";
import Footer from "../../components/Footer";
import FormCheckout from "../../components/FormCheckout";
import Navbar from "../../components/Navbar";
import { getData } from "../../utils/fetchData";
import { formatDate } from "../../utils/formatDate";
import { useEffect } from "react";

export default function Dashboard({ data }) {
  // Fungsi untuk memformat harga
  const formatPrice = (price) => {
    return price
      .toLocaleString("id-ID", { style: "currency", currency: "IDR" })
      .replace(/(\.|,)00$/g, "");
  };

  return (
    <>
      <Head>
        <title>NgeventKuy! || Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <section className="bg-navy">
        <div
          className="container bg-navy text-white py-5"
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <h1 className="text-center mb-4">History Order Tickets</h1>
          <div style={{ width: "100%", maxWidth: "800px" }}>
            {data.map((item) => (
              <div
                key={item._id}
                style={{
                  borderBottom: "1px solid #ffffff",
                  paddingBottom: "0.5rem",
                  marginBottom: "1rem",
                  display: "flex",
                  flexDirection: "column", // Stack vertically on mobile
                  alignItems: "flex-start", // Align items to the start on mobile
                }}
              >
                <div style={{ marginBottom: "0.25rem" }}>
                  <h3>{item.historyEvent.title}</h3>
                </div>
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    marginBottom: "0.5rem",
                  }}
                >
                  <img
                    src="/icons/ic-marker-white.svg"
                    alt=""
                    style={{ marginRight: "0.25rem" }}
                  />
                  <span>{item.historyEvent.venueName}</span>
                </div>
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    marginBottom: "0.5rem",
                  }}
                >
                  <img
                    src="/icons/ic-time-white.svg"
                    alt=""
                    style={{ marginRight: "0.25rem" }}
                  />
                  <span>
                    {moment(item.historyEvent.date).format("HH.MM A")}
                  </span>
                </div>
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    marginBottom: "0.5rem",
                  }}
                >
                  <img
                    src="/icons/ic-calendar-white.svg"
                    alt=""
                    style={{ marginRight: "0.5rem" }}
                  />
                  <span>{formatDate(item.historyEvent.date)}</span>
                </div>
                <div
                  style={{
                    textAlign: "right",
                    width: "100%",
                    marginTop: "0.5rem",
                  }}
                >
                  <span style={{ fontWeight: "bold", fontSize: "2rem" }}>
                    {formatPrice(item.totalPay)}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData(`/api/v1/orders`, {}, context.req.cookies.token);

  const res = req.data;

  console.log(res);

  return {
    props: { data: res },
  };
}
